name: PR - CI
on: 
  pull_request:
    paths-ignore:	
      - '**/*.md'	
      - 'mkdocs.yml'	
      - 'src/docs/**/*'
    branches:
      - dev
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
jobs:
  build_test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    name: Build & Test
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core 3.1 on ${{ matrix.os }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.405
    - name: Setup .NET Core 5.0 on ${{ matrix.os }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.102
    - name: Build
      run: |
        dotnet build --configuration Release
    - name: Unit Tests
      run: |
        dotnet test -c Release --no-restore --no-build ./test/OrchardCore.Tests/OrchardCore.Tests.csproj 
    - name: Functional Tests
      if: matrix.os == 'ubuntu-latest'
      run: |
        cd test/Functional
        npm install
        npm run cms:test
        npm run mvc:test
    - uses: actions/upload-artifact@v2
      if: matrix.os == 'ubuntu-latest' && failure()
      with:
        name: functional-test-failure
        path: |
          test/Functional/cms-tests/cypress/screenshots
          src/OrchardCore.Cms.Web/App_Data_Tests/logs
  